---
AllCops:
    DisplayCopNames: true
    Exclude:
    - 'lib/aws_assume_role/vendored/**/*.rb'

Metrics/MethodLength:
    Enabled: false

Metrics/AbcSize:
    Enabled: false

Metrics/BlockLength:
    Enabled: false

Metrics/ClassLength:
    Enabled: false

Metrics/CyclomaticComplexity:
    Enabled: false

Metrics/PerceivedComplexity:
    Enabled: false

Style/IndentationWidth:
    Width: 4

Style/IndentHeredoc:
    Enabled: false

Style/TrailingCommaInArguments:
    EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
    EnforcedStyleForMultiline: comma

Style/ClassAndModuleChildren:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/VariableName:
    Enabled: false

Style/StringLiterals:
    EnforcedStyle: double_quotes

Style/MethodMissing:
    Enabled: false

Style/TrivialAccessors:
    Enabled: false

Metrics/LineLength:
  Max: 140
