language: ruby
sudo: false
script: bundle exec rake
jobs:
  include:
    - stage: test
      rvm: 2.2
      script: bundle exec rake
    - rvm: 2.3
      script: bundle exec rake
    - stage: deploy
      rvm: 2.3
      script: bundle exec rake setup_credentials && chmod 0600 /home/travis/.gem/credentials && bundle exec rake publish
      secure: "VQtFNu/kHZdKrmURVx4cPgW4uo+7klWQkMA9fJVYvyQzYoELmo/Q5L/75AE8mzNzXHTsRfRu/ggA5vlyHtXpQguz0Tz/pZ0pi24HKIkFFYzmXL4xb2depLTLu2DBFOZUPhshyIEJ9rVhT4sE2E7TOZErhJ1od5NQFAn1I17NyF3qStiORpjptSeU12OReNrlx0kquiZjyYklxO1M3ybzWHLmxVYNRjabqjkm0YB2NrTTFraeivixpRLSolsbzxRBxZwT7UOv/zbEcp9RGZDHxtxcD71rq8KaCXWzscErrcCiJtzrnHUHjAULFFkCPD+rCSbJJkydjxFjg3lVJbf5JulZYr4VzWLimjLUZv4HeeN+bvtwrPKCOe0KxRnsAr4kieX16MO/5ehkNHzjFyiSfkVGWK0uoWGNE9MdCwHLo+o+cz3XoKMQFZhmSheuxKKibr0m9PedynQQdg7bc3kB3UaYurrDs5ldb8e97BnZJrTaTD3/8vaWv30MFuZ+Nw/Hi2uEP7nIZoZfz2D8S6a83YLAC7YAfnf/1lMCU2mfBSLg6L8H26h5bmOUfg10ZNiJDW0g0WqbjbI0xUcMjHd5qdPYP1bH4qtXAdDp9I09NHpteEo42P58milj7n7qWAx+TiRnQR0/jBJL+dXGwYRfoXuzI+4QDy8sq20Cvi34RPU="

stages:
  - name: test
  - name: deploy
    if: tag =~ ^v
notifications:
  slack:
    secure: RmJmJSSDI8qdIpM2KKYoXX2mpcL85YZ9r9gF4rauZH9TuqnYOPP3kQ5iYJsE0VUTuZpuvQ8Axoux5IQr+IDK7kMrmrI0iaZp1dAR9tGK+aLF73sprOmQEou6HIoDs97UQhOWlsAUR8max/7WYdJYJ1o78dqavfFtOy0VcHCkUMRf+WxcKzz+8MunsocIYi0HXuz5vC3RAZCOaK2h8epXzmnWq0ke8YeTmddpDWC85wzeDNjA9T1j5WD+y6gC9F0vyaqVqDCsCXlbRKZl7a1TU9QGDVyBzowoGsWmTpFR80v4CKofAn6nnMRqblwATOS1jMT+HC+Yku29qFzXPugYa2KAUSQaYQiOe+TE5IDa2Exe/57ZQCOq4ve8gKSE9aQXh4Riq3u8qccM+UeoQdcwgXQIciTeWjqi4LQro6Dbyrv8XrUbxdG0VPsWmf49jbWgq6PPAJqdcbXr9eGb+81uJ2REa1vhDYZu4T3JHv4erd5QlyYWzeBJ/LMQav/C5mnMF43jg8DzZ2g0BZBao/reO9xcZre/ka8eOus9Ll1i+8PCxmFZMx2KDPC9i5R7bXL/CwPBjzFInmvHM0cgKjxrRSY6xMWSPyBbgdsKJl2qag74K5xG+2VPlMcVx0ikTKVjsja5iPlOYKhflGAfCKvpzPcd2QoEWg8jZYqZtO9Nj+M=
    on_success: change
    on_failure: change
