language: ruby
sudo: false
script: bundle exec rake
jobs:
  include:
    - stage: test
      rvm:
      - 2.2
      - 2.3
      script: bundle exec rake
    - stage: deploy
      rvm: 2.3
      script: bundle exec rake setup_credentials && bundle exec rake publish
      secure: "nyqCK9Yul0dJCou/Txw8DQ9eXUZGe+CbNj8nXUvmqu0PRMiWesrqzh3XvZR8j2WS+LSfpWQ8esu6RPIW8HND0FA8byeUQhB2UraafnEPGljjwbby2L+Y38JPAg3d8cWvH1jLNUsUAMOFjw2kcCtdnaolVmGEu0EuQ5aITPBdMNjnwiCd4lYD+a17bpX0WCKjOHcgRH6HoQeU6BEnCNE7AmpA1OXbry1EMA/D8P6g1ez51iibf9LYcyfy3NqUIRavhpRrUAvvHJbIwFOHK06Y19OYKE6OB443mb9A9o8zn67aqJ0fSVRK+8RK/p54XtF8nQ8FN/ccnpkekA1BlA2wgxbdxFbzX+Pm/SRZXLyCjdTO9CcgTkxb9+FGJv8/VYaPrdoVx9iMIzg8flh7TfEuiXX8/H1btelV+LDHa9O6qtr/bmZx7J/uCgt32tV2eTqsYsKxvy1Afs3liXsg4JCrhew/59oJPDFezv8vVweD/iGykQKyTqWwcMfPqVJtfJf/jTpTFQ8U4XZzjVxBPROrFiK3IuDQGVUDsoLuoPD8gSA/o36/p5wJSDTILPdFrA2Gl74LoohO+kjCC4fFRr/MCiEJbFQtgqEhSVi+8/gO1UVrgRh9kYSWYcHDtitPiGrNx3rqZoGjRDHMDUhDS0WG9+iWZ9UnyR2MeYpxtCp5YW4="
stages:
  - name: test
  - name: deploy
    if: tag =~ ^v
notifications:
  slack:
    secure: RmJmJSSDI8qdIpM2KKYoXX2mpcL85YZ9r9gF4rauZH9TuqnYOPP3kQ5iYJsE0VUTuZpuvQ8Axoux5IQr+IDK7kMrmrI0iaZp1dAR9tGK+aLF73sprOmQEou6HIoDs97UQhOWlsAUR8max/7WYdJYJ1o78dqavfFtOy0VcHCkUMRf+WxcKzz+8MunsocIYi0HXuz5vC3RAZCOaK2h8epXzmnWq0ke8YeTmddpDWC85wzeDNjA9T1j5WD+y6gC9F0vyaqVqDCsCXlbRKZl7a1TU9QGDVyBzowoGsWmTpFR80v4CKofAn6nnMRqblwATOS1jMT+HC+Yku29qFzXPugYa2KAUSQaYQiOe+TE5IDa2Exe/57ZQCOq4ve8gKSE9aQXh4Riq3u8qccM+UeoQdcwgXQIciTeWjqi4LQro6Dbyrv8XrUbxdG0VPsWmf49jbWgq6PPAJqdcbXr9eGb+81uJ2REa1vhDYZu4T3JHv4erd5QlyYWzeBJ/LMQav/C5mnMF43jg8DzZ2g0BZBao/reO9xcZre/ka8eOus9Ll1i+8PCxmFZMx2KDPC9i5R7bXL/CwPBjzFInmvHM0cgKjxrRSY6xMWSPyBbgdsKJl2qag74K5xG+2VPlMcVx0ikTKVjsja5iPlOYKhflGAfCKvpzPcd2QoEWg8jZYqZtO9Nj+M=
    on_success: change
    on_failure: change
