language: ruby
sudo: false
script: bundle exec rake
jobs:
  include:
    - stage: test
      rvm: 2.2
      script: bundle exec rake
    - rvm: 2.3
      script: bundle exec rake
    - stage: deploy
      rvm: 2.3
      script: bundle exec rake setup_credentials && chmod 0600 /home/travis/.gem/credentials && bundle exec rake publish
      secure: "mb5ctlJLoQkbDKh7/yeUfPf4MeRQIkhlssMc3BRKwZpK0ohXzHPGA0lAOIjSUCu4EyNyAo5bIq10lc2NX108IoOZ+mNl1NuuBaCx/pCZMtEXN5qBY+SvK6m7KpEoKbxyojOgRaR6jFYipPHtw0rAaWBbFgs5Vtr2QK8sU97dTfxtwSWTswmC1VuwvjBQxjGslJ/HW8zf+MevA490pxU+k2crbg4asNuscdSoIfJgKVScKbhybkyAxJ9SYTf1Yt5wVton16ADIXx/ugKYUTSUNxCTI6rHxK+/+fjtojAXWrWvgjTe+6jqSJvYRdITaEzmPcbAbl6AVwzlX8iiQ7dabD2PPUyv8RB0tqWfbqTHxeySTyycJ8/MAGErs7Vd8Qs66p9r4Kzb8P4Ezgoeao72Q1IZ0HZK7e75+awdfM81xZgOkhT692Ocnmtnd92TEh/Y3iFYfbMdRjwD7JIg969b1s8L5rt4wwwIJ3jp+Enb8TMzzVHJ9UD0oWe1n4LWZhv3pJHeSJBiQoGUY14HuutjWJQkFpLUbM8xv9PJvU7AhouflUbX4RU3KOh6LF4pL6nbDB1kFUTXCPJdJukQqtLI48G9bWqN2OktLMFlF8HliaSUJsaLPEumiYmT2djY3poembcazQNN9SOo7189TrxA04fv47dMG0eNcZZFlTmO4Ds="
stages:
  - name: test
  - name: deploy
    if: tag =~ ^v
notifications:
  slack:
    secure: RmJmJSSDI8qdIpM2KKYoXX2mpcL85YZ9r9gF4rauZH9TuqnYOPP3kQ5iYJsE0VUTuZpuvQ8Axoux5IQr+IDK7kMrmrI0iaZp1dAR9tGK+aLF73sprOmQEou6HIoDs97UQhOWlsAUR8max/7WYdJYJ1o78dqavfFtOy0VcHCkUMRf+WxcKzz+8MunsocIYi0HXuz5vC3RAZCOaK2h8epXzmnWq0ke8YeTmddpDWC85wzeDNjA9T1j5WD+y6gC9F0vyaqVqDCsCXlbRKZl7a1TU9QGDVyBzowoGsWmTpFR80v4CKofAn6nnMRqblwATOS1jMT+HC+Yku29qFzXPugYa2KAUSQaYQiOe+TE5IDa2Exe/57ZQCOq4ve8gKSE9aQXh4Riq3u8qccM+UeoQdcwgXQIciTeWjqi4LQro6Dbyrv8XrUbxdG0VPsWmf49jbWgq6PPAJqdcbXr9eGb+81uJ2REa1vhDYZu4T3JHv4erd5QlyYWzeBJ/LMQav/C5mnMF43jg8DzZ2g0BZBao/reO9xcZre/ka8eOus9Ll1i+8PCxmFZMx2KDPC9i5R7bXL/CwPBjzFInmvHM0cgKjxrRSY6xMWSPyBbgdsKJl2qag74K5xG+2VPlMcVx0ikTKVjsja5iPlOYKhflGAfCKvpzPcd2QoEWg8jZYqZtO9Nj+M=
    on_success: change
    on_failure: change
